name: track_trip
description: A trip planning and budgeting app.
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: 5.5.3
  cloud_firestore: ^5.6.7
  provider: ^6.0.5                   # State management
  intl: ^0.18.1                      # Format tanggal, angka, mata uang
  shared_preferences: ^2.2.0        # Local storage (key-value)
  flutter_local_notifications: ^14.1.1  # Local notifications
  table_calendar: ^3.0.9            # Calendar UI widget
  fl_chart: ^0.63.0                 # Chart/grafik visualisasi
  uuid: ^3.0.7                       # Generate UUID untuk ID unik
  cupertino_icons: ^1.0.8           # iOS-style icons

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0             # Linting rules & best practices